config/routes.rb
PjaxSample::Application.routes.draw do
  root :to => 'examples#index'
  resources :examples

end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render_to_pjax(action)
    render action: action, :layout => pjax?
  end

  def pjax?
    env['HTTP_X_PJAX'].blank?
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
    @examples = Example.all

    render_to_pjax :index
  end

  def show
    @example = Example.find(params[:id])

    render_to_pjax :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Born at</th>
    <th></th>
  </tr>

  <% @examples.each do |example| %>
    <tr>
      <td><%= example.name %></td>
      <td><%= example.age %></td>
      <td><%= example.born_at %></td>
      <td><%= link_to 'Show', example, class: "btn info" %></td>
    </tr>
  <% end %>
</table>

app/views/examples/show.html.erb
<p>
  <b>Name:</b>
  <%= @example.name %>
</p>

<p>
  <b>Age:</b>
  <%= @example.age %>
</p>

<p>
  <b>Born at:</b>
  <%= @example.born_at %>
</p>


<%= link_to 'Back', examples_path, class: "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PjaxSample</title>
    <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="content">
        <div class="page-header">
          <h1>Listing examples <small>pjax example</small></h1>
        </div>
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>